### ISSUE TITLE
Folly-0.1.3.0 fails to build

### ISSUE THREAD

**Issue by rzil** [dillonhuff/Folly#2]
I'm trying to build Folly-0.1.3.0 using cabal and GHC 7.8.3. It fails with

```
src/Folly/Resolution.hs:9:8:
    Could not find module ‘Folly.Theorem’
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
Folly-0.1.3.0 failed during the building phase. The exception was:
ExitFailure 1
```

**Comment by dillonhuff** [comment]
I fixed some issues related to implementation of Monad/Applicative in the Error datatype and put a new version (labeled 0.1.4.0) on github and hackage. The package version does not show up yet (for me at least) when I try to do cabal install Folly, but when I do:

mkdir dummy
cd dummy
git clone https://github.com/dillonhuff/Folly.git
cd Folly
cabal install

The package installs correctly. Bear in mind that I am using ghc-7.10.2 for OS X.

Let me know if that fixed the problem.

**Comment by rzil** [comment]
I've upgraded my GHC to 7.10.2 but it still does not build when I run 
cabal install Folly. See below

```
src/Folly/Resolution.hs:9:8:
     Could not find module ‘Folly.Theorem’
     Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
Folly-0.1.4.0 failed during the building phase. The exception was:
ExitFailure 1
```

If I clone the git repo and run cabal install as you suggested then it 
builds. I think there is a problem with the package on Hackage.

Ruben

**Comment by dillonhuff** [comment]
After a few more fixes to the .cabal file things now build when I do

cabal install Folly

Let me know if you still have build problems.

**Comment by rzil** [comment]
It does build now. There is another problem, however. Resolution does 
not seem to work. That is, unless I'm missing something. Here's an 
example.

```
module FollyTest where

import Folly.Formula
import Folly.Resolution
import Folly.Theorem

-- This says that all groups are commutative.
-- It should be False.
-- Instead I'm getting True.
test = isValid non_thm

non_thm = theorem groupWithEquals (fa (var "x") (fa (var "y") (pr "=" 
[func "*" [var "x",var "y"],func "*" [var "y",var "x"]])))

equalityAxioms :: [Formula]
equalityAxioms =
   [(fa (var "x") (pr "=" [var "x", var "x"])),
    (fa (var "x") (fa (var "y") (imp (pr "=" [var "x", var "y"]) (pr "=" 
[var "y", var "x"])))),
    (fa (var "x") (fa (var "y") (fa (var "z") (imp (con (pr "=" [var 
"x", var "y"]) (pr "=" [var "y", var "z"])) (pr "=" [var "x", var 
"z"])))))]

groupWithEquals =
   [(fa (var "x") (te (var "y") (con (pr "=" [func "*" [var "x", var 
"y"], constant "1"]) (pr "=" [func "*" [var "y", var "x"], constant 
"1"])))),
    (fa (var "x") (fa (var "y") (fa (var "z") (pr "=" [func "*" [var 
"x", func "*" [var "y", var "z"]], func "*" [func "*" [var "x", var 
"y"], var "z"]])))),
    (fa (var "x") (con (pr "=" [func "*" [var "x", constant "1"], var 
"x"]) (pr "=" [func "*" [constant "1", var "x"], constant "x"])))] ++ 
equalityAxioms
```

Ruben

**Comment by dillonhuff** [comment]
Yes, that appears to be a bug. I will let you know when I have fixed it.

**Comment by dillonhuff** [comment]
I believe the bug is fixed. It was caused by Skolem function name collision in the preprocessor. The example you gave now seems to take forever to run, so it is not possible to know for sure, but since SAT for FOL is only semi-decidable this is a danger that "comes with the territory".

If you come across any other problems please open a new issue and let me know.

Thanks!
